export const POST_LOGIN = 'POST_LOGIN'
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS'
export const POST_LOGIN_FAILED = 'POST_LOGIN_FAILED'

export const AUTH_INFO = 'AUTH_INFO'
export const AUTH_INFO_SUCCESS = 'AUTH_INFO_SUCCESS'
export const AUTH_INFO_FAILED = 'AUTH_INFO_FAILED'

export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'