export const URL_POST_LOGIN = 'login'
export const URL_GET_AUTH = 'auth-info'
export const URL_DELETE_LOGOUT = 'logout'
export const URL_POST_PROFIL = 'edit-profile'

export const URL_GET_JABATAN = 'jabatan'
export const URL_POST_JABATAN = 'jabatan'
export const URL_EDIT_JABATAN = 'jabatan/:id'
export const URL_DELTE_JABATAN = 'jabatan/:id'

export const URL_GET_USERS = 'users'
export const URL_USERS_BY_ID = 'users/:id'

export const URL_PRESENCE = 'presence'
export const URL_PRESENCE_USER = 'presence-user'
export const URL_COUNT_PRESENCE_USER = 'count-presence'
export const URL_ADD_PRESENCE_IN = 'add-presence-in'
export const URL_ADD_PRESENCE_OUT = 'add-presence-out'
export const URL_PRESENCE_UPDATE = 'presence/:id/update-status'
export const URL_LEAVE = 'leave'
export const URL_LEAVE_USER = 'leave-user'
export const URL_ADD_LEAVE = 'add-leave'
export const URL_LEAVE_UPDATE = 'leave/:id/update-status'

export const URL_SALARY = 'salary'
export const URL_SALARYU = 'salaryU'
export const URL_SALARY_UPDATE = 'salary/:id/update-status'

export const URL_COUNT_PRESENCE_TODAY = 'presence-count-today'
export const URL_COUNT_PRESENCE = 'presence-count'
export const URL_USER_COUNT = 'users-count'